name: Deploy to Google App Engine
on:
  push:
    branches:
      - deploy

jobs:
  Deploy_GAE:
    name: GAE Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Load configs and env vars
      run: |
        echo "${{secrets.ENV_VARS}}" > .env

    - name: 'Auth GCP'
      uses: 'google-github-actions/auth@v0.2.0'
      with:
        project_id: ${{secrets.GCP_PROJECT}}
        credentials_json: ${{ secrets.GCP_CREDENTIALS}}

    - name: 'Deploy'
      uses: 'google-github-actions/deploy-appengine@v0.2.0'
      with:
        working-directory: ./nk-ms
        deliverables: app.yaml
        project_id: ${{secrets.GCP_PROJECT}}
        credentials_json: ${{ secrets.GCP_CREDENTIALS}}
