name: Deploy to Google App Engine
on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nk-ms
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{ secrets.gcp_credentials }}
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
