name: Deploy to Google App Engine
on:
  push:
    branches:
      - deploy
defaults:
  run:
    working-directory: ./app

jobs:
  build:
    name: GAE Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nk-ms
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.gcp_credentials }}